let a = 20
let b = 10
console.log("a = " + a)
console.log("b = " + b)
console.log("a + b = " + (a + b))
console.log("a - b = " + (a - b))
console.log("a * b = " + (a * b))
console.log("a / b = " + (a / b))
console.log("a % b = " + (a % b))